### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by cmyr** [simoncozens/boulmer#2]
I'm investigating adding python bindings directly to norad, and I'm trying to set up my development environment. I sense I'm more or less following in your footprints; in particular, the first thing I want to do is copy over the tests from ufoLib2 and get set up so that I can run them.

So a simple question: in boulmer, how do I actually get the tests to run? I have a virtualenv setup, I have pytest, but I'm not sure... how to install the boulmer package? I've tried all of `maturin develop`, `pip install .`, `python setup.py install`; in all cases if I run `pytest` I get an immediate `E   ModuleNotFoundError: No module named 'boulmer'`.

I'm able to get this working if [I add `contest.py` to the root of the directory](https://stackoverflow.com/questions/49028611/pytest-cannot-find-module), but I'm wondering if there's a better way?

**Comment by chrissimpkins** [comment]
Does it work from a pytest executable installed in the venv?  I've run into this issue with system-installed pytest after running `maturin develop`

```
$ .venv/bin/pytest
```

**Comment by cmyr** [comment]
thanks @chrissimpkins it looks like that was at least part of the problem. :)

**Comment by chrissimpkins** [comment]
> thanks @chrissimpkins it looks like that was at least part of the problem. :)

np!
